import { Network, Users } from "lucide-react";

export function LandingNetwork({ hasPlans }: { hasPlans: boolean }) {
  return <section id="network" className="relative scroll-mt-24 overflow-hidden border-y border-border/70 bg-card/30 py-20 sm:py-28"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_60%_100%_at_90%_50%,rgb(37_99_255_/_0.10),transparent_70%)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 sm:px-6 lg:grid-cols-[0.92fr_1.08fr] lg:items-center lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Referral structure</p><h2 className="mt-4 text-3xl font-black tracking-[-0.04em] sm:text-4xl">A network designed around two meaningful levels.</h2><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">Share your referral code, grow your network and earn commissions according to your active plan&apos;s configured referral structure.</p><div className="clay-sm mt-7 inline-flex items-center gap-3 px-4 py-3 text-sm text-muted-foreground"><Network size={18} className="text-primary" /> No Level 3. No hidden layers.</div></div><NetworkDiagram hasPlans={hasPlans} /></div></section>;
}

function NetworkDiagram({ hasPlans }: { hasPlans: boolean }) {
  const planDetail = hasPlans ? "Configured per active plan" : "Configured by your plan";
  return <div className="clay relative mx-auto w-full max-w-xl p-5 sm:p-8"><div className="absolute left-1/2 top-[26%] h-[16%] w-px -translate-x-1/2 bg-primary/35" /><div className="absolute left-[25%] top-[42%] h-px w-1/2 bg-primary/35" /><div className="absolute left-[25%] top-[42%] h-[12%] w-px bg-primary/35" /><div className="absolute right-[25%] top-[42%] h-[12%] w-px bg-primary/35" /><DiagramNode className="relative z-10 mx-auto" title="You" subtitle="Your referral code" icon="V" primary /><p className="mt-8 text-center text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">Level 1</p><div className="relative z-10 mt-3 grid grid-cols-2 gap-4"><DiagramNode title="Direct referral" subtitle={planDetail} icon="1" /><DiagramNode title="Direct referral" subtitle="Your first-level connection" icon="1" /></div><p className="mt-7 text-center text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">Level 2</p><div className="relative z-10 mt-3 grid grid-cols-2 gap-4"><DiagramNode title="Second-level referral" subtitle={planDetail} icon="2" /><DiagramNode title="Second-level referral" subtitle="Through your Level 1 network" icon="2" /></div><div className="mt-6 flex items-center justify-center gap-2 text-xs text-muted-foreground"><Users size={14} className="text-primary" /> Commission rates remain plan-specific.</div></div>;
}

function DiagramNode({ className = "", title, subtitle, icon, primary = false }: { className?: string; title: string; subtitle: string; icon: string; primary?: boolean }) { return <div className={`${className} min-w-0 ${primary ? "clay-primary border-primary/35" : "clay-sm"} px-3 py-3 text-center sm:px-4`}><span className={`mx-auto flex size-8 items-center justify-center rounded-xl text-xs font-black ${primary ? "bg-primary-foreground/15 text-primary-foreground" : "bg-primary/15 text-primary"}`}>{icon}</span><p className={`mt-2 text-xs font-bold sm:text-sm ${primary ? "text-primary-foreground" : "text-foreground"}`}>{title}</p><p className={`mt-1 text-[10px] leading-4 ${primary ? "text-primary-foreground/75" : "text-muted-foreground"}`}>{subtitle}</p></div>; }
