import { Link } from "react-router-dom";
import { motion } from "motion/react";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button.tsx";
import { formatPKR } from "@/lib/format.ts";

export function LandingPlans({ plans }: { plans: any[] | undefined }) {
  return <section id="plans" className="scroll-mt-24 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="flex max-w-3xl flex-col gap-4"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Membership plans</p><h2 className="text-3xl font-black tracking-[-0.04em] sm:text-4xl">Choose the membership that fits your next step.</h2><p className="text-base leading-7 text-muted-foreground">Review the available plan details and referral structure before creating your Valtora account.</p></div>{plans === undefined ? <PlanSkeletons /> : plans.length ? <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{plans.map((plan: any, index: number) => <PlanCard key={plan._id} plan={plan} featured={index === 1} index={index} />)}</div> : <div className="clay-card mt-12 p-8 text-sm text-muted-foreground">Plans will appear here once configured in the admin panel.</div>}</div></section>;
}

function PlanCard({ plan, featured, index }: { plan: any; featured: boolean; index: number }) { return <motion.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.42, delay: index * 0.07 }} className={`clay-card relative flex min-w-0 flex-col p-6 transition-all duration-300 hover:-translate-y-1 ${featured ? "border-primary/45 shadow-[0_20px_60px_rgb(255_106_0_/_0.16),inset_0_1px_0_rgb(255_255_255_/_0.8)]" : "hover:border-primary/25"}`}>
    {featured && <span className="absolute right-5 top-5 rounded-full border border-primary/25 bg-primary/15 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-primary">Featured</span>}<p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">{plan.name}</p><p className="mt-5 break-words text-4xl font-black tracking-[-0.05em] sm:text-[2.65rem]">{formatPKR(plan.price)}</p><p className="mt-2 text-sm text-muted-foreground">Membership plan</p><div className="my-7 h-px bg-border/80" /><div className="space-y-4 text-sm"><CommissionRow label="Level 1 commission" value={plan.level1Commission} /><CommissionRow label="Level 2 commission" value={plan.level2Commission} /><div className="flex items-start gap-2 text-muted-foreground"><Check size={16} className="mt-0.5 shrink-0 text-primary" />Rates follow this plan&apos;s configured referral structure.</div></div><Button asChild className="mt-8 h-11 w-full rounded-xl"><Link to="/register">Select {plan.name} <ArrowRight size={15} /></Link></Button>
  </motion.article>; }
function CommissionRow({ label, value }: { label: string; value: unknown }) { return <div className="flex items-center justify-between gap-3"><span className="text-muted-foreground">{label}</span><strong className="shrink-0 text-foreground">{String(value)}%</strong></div>; }
function PlanSkeletons() { return <div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="clay-card h-[21rem] animate-pulse" />)}</div>; }
